=head1 NAME

pdf_downsample downsamples all images in a given pdf file to a given resolution 
using ghostscript.

=head1 DESCRIPTION

this program uses ghostscript to let you downsample all images in a pdf to a 
resolution given by you. 

surely this is not the first script for that job, e.g.
 http://www.alfredklomp.com/programming/shrinkpdf/
is an older example. However, the aim of this script is, to let you choose the 
resolution.

=head1 MOVED

moved to gitlab: https://gitlab.com/wp-seth/pdf_downsample
